# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Heroku Docker Registry'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      registry.heroku.com/pet-game-dev/web:$(Build.BuildId)
      registry.heroku.com/pet-game-dev/web:latest
  displayName: 'Heroku - Build and Push container'
