version: "3.7"

services:
  devdb:
    image: "postgres:alpine"
    container_name: petgame_devdb
    restart: unless-stopped
    env_file: src/devdb/.env
    volumes:
      # Timezone
      - '${LOCAL_TIME_MOUNT:-/etc/localtime}:/etc/localtime:ro'
      # Data directory
      - './src/devdb/data:/var/lib/postgresql/data'
    ports:
      - '5432:5432/tcp'
  api:
    image: "pet-game:latest"
    build: ./src/api
    container_name: petgame_api
    restart: unless-stopped
    environment:
      Auth0__ClientSecret: "${DOCKER_API_AUTH0_CLIENT_SECRET}"
      DATABASE_URL: "${DOCKER_DATABASE_URL}"
      PORT: "${DOCKER_PORT}"
    ports:
      # @TODO change production port
      - '5000:${DOCKER_PORT}/tcp'