# Pipeline triggers
trigger: none
pr:
- master

# Pipeline config
pool:
  vmImage: 'ubuntu-latest'

# Jobs
jobs:
# Build/Test API
- job: build_test_api
  displayName: "Build & Test API"
  steps:
  # Build project
  - task: DotNetCoreCLI@2
    displayName: "Build project"
    inputs:
      command: 'build'
      projects: 'src/api/PetGame.sln'
  # Run tests
  - task: DotNetCoreCLI@2
    displayName: "Run test"
    inputs:
      command: 'test'
      projects: 'src/api/PetGame.sln'
# Build/Test WWW
- job: build_test_www
  displayName: "Build & Test WWW"
  steps:
  # npm install
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'src/www'
  # npm run test
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'src/www'
      customCommand: 'test'
  # npm run lint
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'src/www'
      customCommand: 'run lint'
  # npm run type-check
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'src/www'
      customCommand: 'run type-check'
  # npm run build
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'src/www'
      customCommand: 'run run build'
