# Pipeline triggers
trigger: none
pr:
- master

# Pipeline config
pool:
  vmImage: 'ubuntu-latest'

# Jobs
jobs:
- job: build
  displayName: "Verify API"
  steps:
  - task: DotNetCoreCLI@2
    displayName: "Build project"
    inputs:
      command: 'build'
      projects: 'src/api/PetGame.sln'
  - task: DotNetCoreCLI@2
    displayName: "Run test"
    inputs:
      command: 'test'
      projects: 'src/api/PetGame.sln'
